name: Build VMK

on:
  push:
    branches:
      - deploy
  workflow_dispatch:
    inputs:
      reason:
        description: 'Thích thì build thôi'
        required: false
        default: 'Manual build'

jobs:
  build:
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          extra-cmake-modules \
          libfcitx5core-dev \
          libfcitx5config-dev \
          libfcitx5utils-dev \
          libinput-dev \
          libudev-dev \
          g++ \
          golang \
          hicolor-icon-theme \
          pkg-config
      
    - name: Create tarball structure
      run: |
        mkdir -p dist
        sudo make install DESTDIR=$(pwd)/dist PREFIX=/usr

        ls -R dist/
        
    - name: Compress Artifact
      run: |
        tar -czf fcitx5-vmk.tar.gz -C dist .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fcitx5-vmk-package
        path: fcitx5-vmk.tar.gz
        retention-days: 7

    # - name: Create Release
    #   uses: softprops/action-gh-release@v2
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/deploy'
    #   with:
    #     files: fcitx5-vmk.tar.gz
    #     tag_name: v${{ github.run_number }}
    #     name: Release Build ${{ github.run_number }}
    #     body: |
    #       Bản build tự động từ branch deploy.
    #       Lý do: ${{ github.event.inputs.reason || 'Auto build on push' }}
    #     draft: false
    #     prerelease: false
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}